name: Generate Markdown Files

on:
  push:
    paths:
      - 'index.json'
      - 'generate_markdown.py'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Run generator script
      run: |
        python generate_markdown.py

    - name: Commit and push updated Markdown files
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add tools/*.md
        git diff --cached --quiet || git commit -m "Auto-generate or update Markdown files from index.json"
        git push
